// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Tema2_ISP_CTD;

/************************************************************/
/**
 * Enumeratie folosita pentru a marca starile camerei
 */
public enum StariCamera {
	/**
	 * Prima data camera va fi in starea pornita, pregatita pentru a capta imaginea
	 */
	Pornita,
	/**
	 * Dupa ce imaginea a fost cu succes capturata, se va seta aceasta noua stare
	 */
	ImagineCapturata,
	/**
	 * Dupa ce algoritmul de procesare a fost rulat, camera va fi setata cu aceasta stare
	 */
	ImagineProcesata,
	/**
	 * Dupa ce numarul masinii proprietarului a fost reperat, starea va fi aceasta:
	 */
	NrIdentificat,
	/**
	 * Dupa ce datele necesare identificarii automobilului au fost transferate catre un dispozitiv de verificare,
	 * noua stare va fi aceasta:
	 */
	DateTransmise;
};
