// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Tema2_ISP_CTD;

/************************************************************/
/**
 * 
 */
public class Camera {
	/**
	 * 
	 */
	private String idCamera;
	/**
	 * 
	 */
	private String nrInmatriculare;

	/**
	 * 
	 */
	public void procesareImagine() {
	}

	/**
	 * 
	 */
	public void transmitereDate() {
	}

	/**
	 * 
	 */
	private void identificareNrMasina() {
	}

	/**
	 * 
	 */
	public void capturareImagine() {
	}
};
