// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Tema2_ISP_CTD;

/************************************************************/
/**
 * 
 */
public class Date_Rovinieta {
	/**
	 * 
	 * @param ID 
	 */
	public void verificareRovinieta(long ID) {
	}
};
