// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Tema2_ISP_CTD;

/************************************************************/
/**
 * 
 */
public class DispVerificare extends Date_Rovinieta {
	/**
	 * 
	 */
	private String idDispVerif;

	/**
	 * 
	 */
	public void alertarePolitie() {
	}

	/**
	 * 
	 */
	public void listaRoviniete() {
	}

	/**
	 * 
	 */
	public void preluareDateRovinieta() {
	}
};
