// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Tema2_ISP_CTD;

/************************************************************/
/**
 * 
 */
public class Organ_politie extends Date_Rovinieta {
	/**
	 * 
	 */
	private String nume;

	/**
	 * 
	 */
	public void aplicareSanctiune() {
	}
};
