// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Tema2_ISP_CTD;

/************************************************************/
/**
 * 
 */
public class Proprietar_masina extends Date_Rovinieta {
	/**
	 * 
	 */
	private String nume;
	/**
	 * 
	 */
	private String cnp;
	/**
	 * 
	 */
	private String adresa;
	/**
	 * 
	 */
	private Rovinieta rovinieta;

	/**
	 * 
	 */
	public void introducereDate() {
	}
};
