// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Tema2_ISP_CTD;

/************************************************************/
/**
 * 
 */
public class Rovinieta {
	/**
	 * 
	 */
	private String nrInmatriculare;
	/**
	 * 
	 */
	private String serieSasiu;
	/**
	 * 
	 */
	private long idRovinieta;

	/**
	 * 
	 */
	public void afisareDate() {
	}
};
