// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Tema2_ISP_CTD;

/************************************************************/
/**
 * 
 */
public class Sanctiune {
	/**
	 * 
	 */
	private String proba;
	/**
	 * 
	 */
	private String data;
	/**
	 * 
	 */
	private String ora;
	/**
	 * 
	 */
	private String loc;
	/**
	 * 
	 */
	private Organ_politie organPolitie;
	/**
	 * 
	 */
	private Proprietar_masina proprietar;
};
