// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Tema2_ISP_CTD;

/************************************************************/
/**
 * 
 */
public class Date_Rovinieta {
	/**
	 * 
	 * Metoda de baza folosita pentru a verifica rovinieta, putand fi supradefinita in celelalte clase ce deriva din aceasta
	 */
	public int verificareRovinieta(String nrInmatriculare, String serieSasiu) {
		return 1;
	}
};