// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Tema2_ISP_CTD;

/************************************************************/
/**
 * 
 */
public class Camera {
	/**
	 * 
	 */
	private String idCamera;
	/**
	 * 
	 */
	private String nrInmatriculare;
	/**
	 * 
	 */
	private StariCamera StareCam;

	public String getIdCamera() {
		return idCamera;
	}

	public void setIdCamera(String idCamera) {
		this.idCamera = idCamera;
	}

	public String getNrInmatriculare() {
		return nrInmatriculare;
	}

	public void setNrInmatriculare(String nrInmatriculare) {
		this.nrInmatriculare = nrInmatriculare;
	}

	public StariCamera getStareCam() {
		return StareCam;
	}

	public void setStareCam(StariCamera stareCam) {
		StareCam = stareCam;
	}

	/**
	 * 
	 */
	public void identificareNrMasina() {
	}

	/**
	 * 
	 */
	public void capturareImagine() {
	}
};
