// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Tema2_ISP_CTD;

/************************************************************/
/**
 **
 */
public class DispVerificare extends Date_Rovinieta {
	/**
	 * 
	 */
	private static int nrRoviniete;
	/**
	 * 
	 */
	private Rovinieta[] rovinieta;
	
	
	
	public DispVerificare() 
	{
		nrRoviniete = 0;
		rovinieta = null;
	}
	
	public DispVerificare(Rovinieta[] roviniete, int lungime) {
		nrRoviniete = lungime;
		if(roviniete != null) {
			for(int i=0; i<nrRoviniete; ++i)
				rovinieta[i] = roviniete[i];
		}
	}
	
	public Rovinieta getRovinieta(int i) 
	{
		return rovinieta[i];
	}
	
	public Rovinieta[] getRovinieta()
	{
		return rovinieta;
	}

	public void setRovinieta(Rovinieta[] rovinieta, int lungime) 
	{
		rovinieta = new Rovinieta[lungime];
		
		for(int i=0; i < lungime; ++i) {
			this.rovinieta[nrRoviniete] = rovinieta[i];
			nrRoviniete = nrRoviniete +1;
		}
	}
	
	public int getNrRoviniete() {
		return nrRoviniete;
	}
	
	public void adaugaRovinieta(Rovinieta rovinieta) 
	{
		
		if(nrRoviniete > 1) {
			//nrRov =2
			nrRoviniete = nrRoviniete +1; //nrRov = 3
			Rovinieta temp[] = new Rovinieta[nrRoviniete]; 
			
			for(int i=0; i<nrRoviniete-1; ++i)
				temp[i] = this.rovinieta[i];
			
			temp[nrRoviniete-1] = rovinieta;
			
			this.rovinieta = new Rovinieta[nrRoviniete];
			
			for(int i=0; i<nrRoviniete; ++i)
				this.rovinieta[i] = temp[i];
		} 
		else if(nrRoviniete == 1)
		{
			nrRoviniete = nrRoviniete +1;
			Rovinieta temp = this.rovinieta[nrRoviniete-2];
			
			this.rovinieta = new Rovinieta[nrRoviniete]; //marit spatiul la 2
			this.rovinieta[nrRoviniete -2] = temp;       // pe 0 punem temp
			this.rovinieta[nrRoviniete -1] = rovinieta;  // pe 1 punem rovinieta pe care o vrem
		} 
		else {
			nrRoviniete = nrRoviniete +1;
			this.rovinieta = new Rovinieta[nrRoviniete]; //aloc 1 spatiu
			this.rovinieta[nrRoviniete-1] = rovinieta;   // pun pe pozitia 1-1=0 pe rovinieta
		}
		
	}
	
	public boolean scoateRovinieta(Rovinieta rovinieta) {
		boolean ok=false;
		for(int i=0; i<nrRoviniete; ++i) {
			if(ok) {
				this.rovinieta[i-1] = this.rovinieta[i];
			}
			if(this.rovinieta[i] == rovinieta)
				ok=true;
		}
		if(ok) {
			nrRoviniete = nrRoviniete -1;
			return true;
		}
		else return false;
	}
	
	public boolean scoateRovinieta(int numar) {
		if(numar < nrRoviniete) {
			for(int i=numar+1; i<nrRoviniete; ++i) {
				this.rovinieta[i-1] = this.rovinieta[i];
			}
			return true;
		}
		else return false;
	}

	
	public void alertarePolitie(Rovinieta rovinieta) {
		System.out.println("Politia a fost alertata pentru rovinieta cu datele:");
		rovinieta.afisareDate();
		System.out.println("Un agent al politiei va fi trimis catre dumneavoastra!");
	}

	/**
	 * 
	 */
	public void listaRoviniete() {
		
		if(nrRoviniete == 0)
	 		return;
		
		for(int i=0; i<nrRoviniete; ++i)
			rovinieta[i].afisareDate();
	}

	/**
	 * 
	 */
	public boolean preluareDateRovinieta(String serieSasiu, Evidenta evidenta) {
		String nr = "";
		if(evidenta.rovinietaExista(serieSasiu))
			if(evidenta.getNrInmatriculare(serieSasiu) != "")
				nr = evidenta.getNrInmatriculare(serieSasiu);
		if(verificareRovinieta(nr, serieSasiu, evidenta)) return true;
		else return false;
	}
	
	@Override
	public boolean verificareRovinieta(String nrInmatriculare, String serieSasiu, Evidenta evidenta) {
		if(evidenta.rovinietaExista(serieSasiu))
			if(!evidenta.rovinietaExpirata(serieSasiu))
				return true;
		
		Rovinieta temp = new Rovinieta(nrInmatriculare, serieSasiu, 99);
		this.adaugaRovinieta(temp);
		
		System.out.println("Rovinieta expirata! Inceperea procesului de alertare politie!");
		alertarePolitie(temp);
		return false;
	}
};
