// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Tema2_ISP_CTD;

/************************************************************/
/**
 * 
 */
public class Evidenta {
	/**
	 * 
	 */
	private Rovinieta[] rovinieta;
	/**
	 * 
	 */
	private static int nrRovinieta =0;

	/**
	 * 
	 */
	public Evidenta(){
		this.rovinieta = null;
	}
	
	public void afiseazaRoviniete() {
		for(int i=0; i<nrRovinieta; ++i)
			System.out.println(rovinieta[i] + " ");
	}
	
	public Rovinieta[] getRovinieta() {
		return this.rovinieta;
	}

	public void setRovinieta(Rovinieta[] rovinieta, int lungime) {
		for(int i=0; i<lungime; ++i) {
			this.rovinieta[nrRovinieta] = rovinieta[i];
			nrRovinieta = nrRovinieta +1;
		}
	}
	
	public void adaugaRovinieta(Rovinieta rovinieta) {
		this.rovinieta[nrRovinieta] = rovinieta;
		nrRovinieta = nrRovinieta +1;
	}
	
	public boolean scoateRovinieta(Rovinieta rovinieta) {
		boolean ok=false;
		for(int i=0; i<nrRovinieta; ++i) {
			if(ok) {
				this.rovinieta[i-1] = this.rovinieta[i];
			}
			if(this.rovinieta[i] == rovinieta)
				ok=true;
		}
		if(ok) {
			nrRovinieta = nrRovinieta -1;
			return true;
		}
		else return false;
	}
	
	public boolean scoateRovinieta(int numar) {
		if(numar < nrRovinieta) {
			for(int i=numar+1; i<nrRovinieta; ++i) {
				this.rovinieta[i-1] = this.rovinieta[i];
			}
			return true;
		}
		else return false;
	}
	
	public boolean rovinietaExista(String serieSasiu) {
		for(int i=0; i<nrRovinieta; ++i) {
			if( serieSasiu.equals( rovinieta[i].getSerieSasiu() ) ) {
				System.out.println("rovinietaExista() -> Rovinieta are serieSasiu la fel");
				return true;
			}
		}
		return false;
	}
	
	public boolean rovinietaExpirata(String serieSasiu) {
		for(int i=0; i<nrRovinieta; ++i) {
			if( serieSasiu.equals( rovinieta[i].getSerieSasiu() ) ) {
				System.out.println("rovinietaExpirata() -> Rovinieta are serieSasiu la fel");
				if(rovinieta[i].getIsExpired()) return true;
			}
		}
		return false;
	}
	
	public String getNrInmatriculare(String serieSasiu) {
		for(int i=0; i<nrRovinieta; ++i) {
			if( serieSasiu.equals( rovinieta[i].getSerieSasiu() ) )
				return rovinieta[i].getNrInmatriculare();
		}
		return "";
	}
};
