// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Tema2_ISP_CTD;

/************************************************************/
/**
 * 
 */
public class Evidenta {
	/**
	 * 
	 */
	private Rovinieta[] rovinieta;
	/**
	 * 
	 */
	private static int nrRovinieta =0;

	/**
	 * 
	 */
	public Evidenta(){
		this.rovinieta = null;
	}
	
	public Rovinieta[] getRovinieta() {
		return this.rovinieta;
	}

	public void setRovinieta(Rovinieta[] rovinieta, int lungime) {
		this.rovinieta = new Rovinieta[lungime];
		for(int i=0; i<lungime; ++i) {
			this.rovinieta[nrRovinieta] = rovinieta[i];
			nrRovinieta = nrRovinieta +1;
		}
	}
	
	public static int getNrRoviniete() {
		return nrRovinieta;
	}
	
	
	public void afiseazaRoviniete() {
		for(int i=0; i<nrRovinieta; ++i)
			rovinieta[i].afisareDate();
	}
	
	public void adaugaRovinieta(Rovinieta rovinieta) {
		
		if(nrRovinieta > 1) {
			//nrRov =2
			nrRovinieta = nrRovinieta +1; //nrRov = 3
			Rovinieta temp[] = new Rovinieta[nrRovinieta]; 
			
			for(int i=0; i<nrRovinieta-1; ++i)
				temp[i] = this.rovinieta[i];
			
			temp[nrRovinieta-1] = rovinieta;
			
			this.rovinieta = new Rovinieta[nrRovinieta];
			
			for(int i=0; i<nrRovinieta; ++i)
				this.rovinieta[i] = temp[i];
		} 
		else if(nrRovinieta == 1)
		{
			nrRovinieta = nrRovinieta +1;
			Rovinieta temp = this.rovinieta[nrRovinieta-2];
			
			this.rovinieta = new Rovinieta[nrRovinieta]; //marit spatiul la 2
			this.rovinieta[nrRovinieta -2] = temp;       // pe 0 punem temp
			this.rovinieta[nrRovinieta -1] = rovinieta;  // pe 1 punem rovinieta pe care o vrem
		} 
		else {
			nrRovinieta = nrRovinieta +1;
			this.rovinieta = new Rovinieta[nrRovinieta]; //aloc 1 spatiu
			this.rovinieta[nrRovinieta-1] = rovinieta;   // pun pe pozitia 1-1=0 pe rovinieta
		}
		
	}
	
	public boolean scoateRovinieta(Rovinieta rovinieta) {
		boolean ok=false;
		for(int i=0; i<nrRovinieta; ++i) {
			if(ok) {
				this.rovinieta[i-1] = this.rovinieta[i];
			}
			if(this.rovinieta[i] == rovinieta)
				ok=true;
		}
		if(ok) {
			nrRovinieta = nrRovinieta -1;
			return true;
		}
		else return false;
	}
	
	public boolean scoateRovinieta(int numar) {
		if(numar < nrRovinieta) {
			for(int i=numar+1; i<nrRovinieta; ++i) {
				this.rovinieta[i-1] = this.rovinieta[i];
			}
			return true;
		}
		else return false;
	}
	
	public boolean rovinietaExista(String serieSasiu) {
		if(nrRovinieta != 0) {
			System.out.println(nrRovinieta);
			this.afiseazaRoviniete();
			for(int i=0; i<nrRovinieta; ++i) {
				System.out.println(rovinieta[i].getSerieSasiu());
				
				if( serieSasiu.equals( rovinieta[i].getSerieSasiu() ) ) {
					System.out.println("rovinietaExista() -> Rovinieta are serieSasiu la fel");
					return true;
				}
			}
		}
		return false;
	}
	
	public boolean rovinietaExpirata(String serieSasiu) {
		for(int i=0; i<nrRovinieta; ++i) {
			if( serieSasiu.equals( rovinieta[i].getSerieSasiu() ) ) {
				System.out.println("rovinietaExpirata() -> Rovinieta are serieSasiu la fel");
				if(rovinieta[i].getIsExpired()) return true;
			}
		}
		return false;
	}
	
	public String getNrInmatriculare(String serieSasiu) {
		for(int i=0; i<nrRovinieta; ++i) {
			if( serieSasiu.equals( rovinieta[i].getSerieSasiu() ) )
				return rovinieta[i].getNrInmatriculare();
		}
		return "";
	}
};
