// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Tema2_ISP_CTD;

/************************************************************/
/**
 * CEva orice nimic oriceseafosjioghiorsh;gia
 */
public class Organ_politie extends Date_Rovinieta {
	/**
	 * 
	 */
	private String nume;

	/**
	 * 
	 */
	public void setNume(String nume)
	{
		this.nume = nume;
	}
	
	public String getNume()
	{
		return this.nume;
	}
	
	public void aplicareSanctiune() 
	{
		
	}
};
