// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Tema2_ISP_CTD;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;

/************************************************************/
/**
 * 
 */
public class Organ_politie extends Date_Rovinieta {
	/**
	 * 
	 */
	private String nume;
	
	private DispVerificare dispverif;
	
	/**
	 * Constructor de baza
	 */
	public Organ_politie() {
		nume = "Gica";
		dispverif = new DispVerificare();
	}
	
	/**
	 * Constructor cu parametrii
	 */
	public Organ_politie(String nume, DispVerificare dispV)
	{
		this.nume = nume;
		dispverif = dispV;
	}
	
	/**
	 *  Getteri si Setteri
	 */
	public void setNume(String nume)
	{
		this.nume = nume;
	}
	
	public String getNume()
	{
		return this.nume;
	}
	
	public DispVerificare getDispVerif() {
		return dispverif;
	}
	
	public void setDispVerif(DispVerificare dispverif) {
		this.dispverif = dispverif;
	}
	
	/**
	 *  Fac override la fct verificareRovinieta din cls Date_Rovinieta 
	 */
	@Override 
	public int verificareRovinieta(String nrInmat, String serieSasiu) {
		int rezultat = dispverif.verificareRovinieta(nrInmat, serieSasiu);
		if( rezultat == 2 || rezultat == 3) 
		{
			Sanctiune s1=aplicareSanctiune();
			return 2;
		}
		return 1;
	}
	
	/**
     * Prin aceasta metoda se primeste semnalul de la un dispozitiv de verificare
     */
	public boolean primireSemnal(String departament) {
		if(departament != null || departament != "") {
			System.out.println("Semnal primit de sectia " + departament);
			trimiterePolitist();
			return true;
		}
    	return false;
   }

   /**
    *  Prin aceasta metoda se asigneaza politistul catre infractor
    */
   public void trimiterePolitist() {
       System.out.println("Politistul " + nume + " a fost trimis catre locatie.");
   }
	
	/**
	 * Metoda de aplicare a sanctiunii cu locul, proba, data si organul de politie ce o aplica
	 */
	public Sanctiune aplicareSanctiune() {
		
		System.out.println("Sanctiunea a fost aplicata!");
		
		String proba = "Rovinieta expirata";
		
		String loc = "DN2";
		
		DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
		Calendar cal = Calendar.getInstance();
		
		
		String data = dateFormat.format(cal.getTime()).toString();
		
		return new Sanctiune(proba, data, loc, this);
		
	}
};