// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Tema2_ISP_CTD;

/************************************************************/
/**
 * 
 */
public class Proprietar_masina extends Date_Rovinieta {
	/**
	 * 
	 */
	private String nume;
	/**
	 * 
	 */
	private String cnp;
	/**
	 * 
	 */
	private String adresa;
	/**
	 * 
	 */
	
	
	public void introducereDate(String nume, String CNP, String adresa)
	{
		this.nume = nume;
		this.cnp = CNP;
		this.adresa = adresa;
	}
	
	public String getNume() {
		return nume;
	}

	public void setNume(String nume) {
		this.nume = nume;
	}

	public String getCnp() {
		return cnp;
	}

	public void setCnp(String cnp) {
		this.cnp = cnp;
	}

	public String getAdresa() {
		return adresa;
	}

	public void setAdresa(String adresa) {
		this.adresa = adresa;
	}

	public Rovinieta getRovinieta() {
		return rovinieta;
	}

	public void setRovinieta(Rovinieta rovinieta) {
		this.rovinieta = rovinieta;
	}

	private Rovinieta rovinieta;

	/**
	 * 
	 */
	public Proprietar_masina(int optiune,String nume, String cnp, String adresa, Rovinieta rovinieta) {
		super();
		if(optiune == 1) {
			this.nume = nume;
			this.cnp = cnp;
			this.adresa = adresa;
			this.rovinieta = rovinieta;
		}
	}
	
	public void introducereDate(Evidenta evidenta) {
	}
};
