// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Tema2_ISP_CTD;

/************************************************************/
/**
 **
 */
public class Rovinieta {
	
	private long idRovinieta;

	private boolean isExpired;

	private String nrInmatriculare;
	
	private String serieSasiu;
	
	/**
	 * Constructor cu parametrii default
	 */
	public Rovinieta()
	{
		idRovinieta = 0000l;
		isExpired = false;
		nrInmatriculare = "";
		serieSasiu = "";
	}
	
	/**
	 * Constructori cu parametri introdusi de la tastatura sau direct
	 */
	public Rovinieta(String nrInmat, String serieSasiu, long idRovinieta)
	{
		nrInmatriculare = nrInmat;
		this.serieSasiu = serieSasiu;
		this.idRovinieta = idRovinieta;
	}
	
	/**
	 *	Constructor de copiere 
	 */
	public Rovinieta(Rovinieta rov)
	{
		this(rov.nrInmatriculare, rov.serieSasiu, rov.idRovinieta);
	}
	
	/**
	 * Setteri si getteri pentru fiecare atribut in parte
	 */
	public String getNrInmatriculare() {
		return nrInmatriculare;
	}

	public void setNrInmatriculare(String nrInmatriculare) {
		this.nrInmatriculare = nrInmatriculare;
	}

	public long getIdRovinieta() {
		return idRovinieta;
	}

	public void setIdRovinieta(long idRovinieta) {
		this.idRovinieta = idRovinieta;
	}

	public boolean getIsExpired() {
		return isExpired;
	}

	public void setIsExpired(boolean isExpired) {
		this.isExpired = isExpired;
	}
	
	public String getSerieSasiu() {
		return this.serieSasiu;
	}
	
	public void setSerieSasiu(String serieSasiu) {
		this.serieSasiu = serieSasiu;
	}
	
	/**
	 * Metoda folosita pentru a returna datele din rovinieta si specificarea starii acesteia(expirata sau nu)
	 */
	public void afisareDate() 
	{
		System.out.println("Rovinieta ID: " + this.idRovinieta);
		System.out.println("Numar inmatriculare: " + this.nrInmatriculare);
		System.out.println("Serie sasiu: " + this.serieSasiu);
		System.out.print("Expirata: ");
		if(getIsExpired())
			System.out.println("Da");
		else System.out.println("Nu");
	}

};
