// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Tema2_ISP_CTD;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;

/************************************************************/
/**
 **
 */
public class Rovinieta {
	
	/**
	 * Id-ul pentru fiecare rovinieta in parte, folosita mai mult pentru identificarea rovinietelor
	 * Folosit pentru a crea id-uri de roviniete
	 */
	private static long id = 159001l;

	/**
	 * Fiecare rovinieta are id-ul ei separat
	 */
	private long idRovinieta;
	
	/**
	 * Variabila folosita pentru a determina valabilitatea unei roviniete
	 */
	private boolean isExpired;

	private String nrInmatriculare;
	
	private String serieSasiu;
	
	/**
	 * Fiecare rovinieta are o data, generata automat
	 * Pentru exemplificarea aplicatiei cat si pentru simplitatea acesteia, am considerat ca o rovinieta este expirata dupa 6 luni de utilizare
	 */
	private Date data;
	
	/**
	 * Constructor cu parametrii default
	 */
	public Rovinieta()
	{
		idRovinieta = id;
		isExpired = false;
		nrInmatriculare = "";
		serieSasiu = "";
		Rovinieta.id += 1;
	}
	
	/**
	 * Constructori cu parametri introdusi de la tastatura sau direct
	 */
	public Rovinieta(String nrInmat, String serieSasiu)
	{
		idRovinieta = Rovinieta.id;
		nrInmatriculare = nrInmat;
		this.serieSasiu = serieSasiu;
		setData(new Date());
		Rovinieta.id += 1;
	}
	
	/**
	 * Constructor prin care se poate seta si id-ul rovinietei
	 * @param nrInmat
	 * @param serieSasius
	 * @param idRov
	 */
	public Rovinieta(String nrInmat, String serieSasius, long idRov)
	{
		this.setNrInmatriculare(nrInmat);
		this.setSerieSasiu(serieSasius);
		this.setIdRovinieta(idRov);
		setData(new Date());
	}
	
	/**
	 *	Constructor de copiere 
	 */
	public Rovinieta(Rovinieta rov)
	{
		this(rov.nrInmatriculare, rov.serieSasiu, rov.getIdRovinieta());
		this.setData(rov.getData());
	}
	
	/**
	 * Setteri si getteri pentru fiecare atribut in parte
	 */
	public String getNrInmatriculare() {
		return nrInmatriculare;
	}
	
	public Date getData() 
	{
		return this.data;
	}
	
	/**
	 * Modalitate de setare a datei Rovinietei
	 * Totodata se verifica si valabilitatea rovinietei
	 * @param data - data noua a Rovinietei
	 */
	public void setData(Date data)
	{
		this.data = data; // se seteaza data rovinietei cu data primita ca parametru
		
		/**
		 * Acesta este un work-around, deoarece metoda getMonth() si getYear() au fost considerate invechite("deprecated")
		 */
		Date date = getData(); // Se creeaza o data noua cu data curenta
		Calendar cal = Calendar.getInstance(); // Se creeaza o instanta a unui calendar
		cal.setTime(date); // Se seteaza data calendarului cu data curenta a rovinietei
		
		// Daca rovinieta a fost creata in acelasi an cu cel curent
		if(Calendar.getInstance().get(Calendar.YEAR) == cal.get(Calendar.YEAR)) {
			// si daca este mai noua de 6 luni
			if(((Calendar.getInstance().get(Calendar.MONTH)) + 1) - (cal.get(Calendar.MONTH) + 1) < 6)
				this.setIsExpired(false); // nu este expirata
			else this.setIsExpired(true); // daca este mai veche, o consideram expirata
		}
		else this.setIsExpired(true); // daca nu este in acelasi an creata, o consideram expirata
	}

	public void setNrInmatriculare(String nrInmatriculare) {
		this.nrInmatriculare = nrInmatriculare;
	}

	public long getIdRovinieta() {
		return idRovinieta;
	}

	public void setIdRovinieta(long idRovinieta) {
		this.idRovinieta = idRovinieta;
	}

	public boolean getIsExpired() {
		return isExpired;
	}

	public void setIsExpired(boolean isExpired) {
		this.isExpired = isExpired;
	}
	
	public String getSerieSasiu() {
		return this.serieSasiu;
	}
	
	public void setSerieSasiu(String serieSasiu) {
		this.serieSasiu = serieSasiu;
	}
	
	/**
	 * Metoda folosita pentru a returna datele din rovinieta si specificarea starii acesteia(expirata sau nu)
	 */
	public void afisareDate() 
	{
		System.out.println("Rovinieta ID: " + this.idRovinieta);
		System.out.println("Numar inmatriculare: " + this.nrInmatriculare);
		System.out.println("Serie sasiu: " + this.serieSasiu);
		System.out.println("Data: " + this.data);
		System.out.print("Expirata: ");
		if(getIsExpired() == true)
			System.out.println("Da");
		else System.out.println("Nu");
	}

};
