// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Tema2_ISP_CTD;

/************************************************************/
/**
 * 
 */
public class Rovinieta {
	/**
	 * 
	 */
	private String nrInmatriculare;
	/**
	 * 
	 */
	private String serieSasiu;
	
	public String getNrInmatriculare() {
		return nrInmatriculare;
	}

	public void setNrInmatriculare(String nrInmatriculare) {
		this.nrInmatriculare = nrInmatriculare;
	}

	public long getIdRovinieta() {
		return idRovinieta;
	}

	public void setIdRovinieta(long idRovinieta) {
		this.idRovinieta = idRovinieta;
	}

	public void setSerieSasiu(String serieSasiu) {
		this.serieSasiu = serieSasiu;
	}

	/**
	 * 
	 */
	private long idRovinieta;

	private boolean isExpired;
	
	/**
	 * 
	 */
	public void afisareDate() 
	{
		System.out.println("Rovinieta ID: " + this.idRovinieta);
		System.out.println("Numar inmatriculare: " + this.nrInmatriculare);
		System.out.println("Serie sasiu: " + this.serieSasiu);
		System.out.print("Expirata: ");
		if(getIsExpired())
			System.out.println("Da");
		else System.out.println("Nu");
	}
	
	//Adaosuri!!!!!!!!!!!!
	public boolean getIsExpired() {
		return isExpired;
	}

	public String getSerieSasiu() {
		return this.serieSasiu;
	}
	
};
