// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Tema2_ISP_CTD;

/************************************************************/
/**
 * 
 */
public class Sanctiune {
	/**
	 * 
	 */
	private String proba;
	/**
	 * 
	 */
	private String data;
	/**
	 * 
	 */
	private String ora;
	/**
	 * 
	 */
	private String loc;
	/**
	 * 
	 */
	private Organ_politie organPolitie;
	/**
	 * 
	 */
	private Proprietar_masina proprietar;
	
	public void setProba(String proba)
	{
		this.proba = proba;
	}
	
	public String getProba()
	{
		return this.proba;
	}
	
	public void setData(String data)
	{
		this.data = data;
	}
	
	public String getData()
	{
		return this.data;
	}
	
	public void setOra(String ora)
	{
		this.ora = ora;
	}
	
	public String getOra()
	{
		return this.ora;
	}
	
	public void setLoc(String loc)
	{
		this.loc = loc;
	}
	
	public String getLoc()
	{
		return this.loc;
	}
	
	public void setOrganPolitie(Organ_politie organPolitie)
	{
		this.organPolitie = organPolitie;
	}
	
	public void setProprietar(Proprietar_masina proprietar)
	{
		this.proprietar = proprietar;
	}
};
