// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Tema2_ISP_CTD;

/************************************************************/
/**
 * 
 */
public enum StariCamera {
	/**
	 * 
	 */
	Pornita,
	/**
	 * 
	 */
	ImagineCapturata,
	/**
	 * 
	 */
	ImagineProcesata,
	/**
	 * 
	 */
	NrIdentificat,
	/**
	 * 
	 */
	DateTransmise;
};
